name: goosdemo
channels:
  - conda-forge
dependencies:
    - jupyterlab
    - matplotlib
    - xarray
    - cartopy
    - cmocean
    - jupyterlab_widgets
    - ipywidgets
    - tqdm
    - erddapy
    - netcdf4
    - scipy
